
nim c -r circle2circle.nim
nim c -r circle2line.nim
nim c -r circle2rect.nim
nim c -r circle2seg.nim
nim c -r convexhull.nim
nim c -r hull2hull.nom
nim c -r line2line.nim
nim c -r line2poly.nim
nim c -r line2rect.nim
nim c -r line2seg.nim
nim c -r point2circle.nim
nim c -r point2line.nim
nim c -r point2point.nim
nim c -r point2rect.nim
nim c -r point2seg.nim
nim c -r poly2circle.nim
nim c -r poly2point.nim
nim c -r poly2poly.nim
nim c -r poly2rect.nim
nim c -r poly2seg.nim
nim c -r rect2rect.nim
nim c -r seg2rect.nim
nim c -r seg2seg.nim
nim c -r tri2point.nim
